import { useEffect, useState } from 'react';
import { ArrowRight, BadgeCheck, Car, ChevronRight, Languages, MapPin, Menu, MessageCircle, Paintbrush, Phone, ShieldCheck, Sparkles, Wrench, X } from 'lucide-react';

type Lang='en'|'ar';
const copy={
 en:{nav:['Home','Services','Process','Transformations','Contact'],eyebrow:'AUTO PAINT • BODY FINISH • SANAYA, QATAR',hero:'Bring Back the Finish Your Car Deserves.',sub:'A premium digital concept for Masud Auto Paint Zone — designed around paint transformation, clear customer contact and a workshop experience that feels professional from the first tap.',quote:'Send Car Photos on WhatsApp',call:'Call Workshop',proof:'5.0 rating • 6 reviews in the supplied business listing',services:'Paint & finish solutions',servicesSub:'A focused service presentation built for customers who care about the final look.',process:'A clearer path from damage to shine',transform:'See the transformation',transformSub:'Before-and-after imagery makes the value of paint restoration immediately visible.',contact:'Ready to refresh your car?',contactSub:'Send photos of the vehicle on WhatsApp and discuss the work directly with the workshop.',location:'551 Sanaya, Qatar',phone:'+974 7127 0891',demo:'Concept website — service descriptions and imagery should be confirmed with Masud before final publication.'},
 ar:{nav:['الرئيسية','الخدمات','الخطوات','قبل وبعد','تواصل معنا'],eyebrow:'دهان سيارات • تشطيب الهيكل • الصناعية، قطر',hero:'أعد لسيارتك اللمعان الذي تستحقه.',sub:'تصور رقمي احترافي لمنطقة مسعود لدهان السيارات، يركز على نتائج الدهان وسهولة التواصل وتجربة عميل واضحة من أول زيارة.',quote:'أرسل صور السيارة عبر واتساب',call:'اتصل بالورشة',proof:'تقييم 5.0 • 6 مراجعات في بيانات النشاط المرسلة',services:'حلول الدهان والتشطيب',servicesSub:'عرض واضح للخدمات للعملاء الذين يهتمون بجودة المظهر النهائي.',process:'من الضرر إلى اللمعان بخطوات واضحة',transform:'شاهد الفرق',transformSub:'صور قبل وبعد توضح قيمة ترميم الدهان بسرعة ووضوح.',contact:'هل تريد تجديد مظهر سيارتك؟',contactSub:'أرسل صور السيارة عبر واتساب وناقش العمل مباشرة مع الورشة.',location:'551 الصناعية، قطر',phone:'+974 7127 0891',demo:'موقع تجريبي — يجب تأكيد تفاصيل الخدمات والصور مع مسعود قبل النشر النهائي.'}
};
const services=[
 ['Full Body Paint','دهان كامل للسيارة','A complete visual refresh for vehicles that need a consistent new finish.','تجديد شامل لمظهر السيارة للحصول على تشطيب متناسق.'],
 ['Panel & Spot Refinishing','دهان الأجزاء والمناطق','Focused refinishing for affected panels, scratches and visible paint damage.','معالجة ودهان الأجزاء المتضررة والخدوش ومشاكل الطلاء الظاهرة.'],
 ['Surface Preparation','تجهيز السطح','Preparation-focused presentation covering sanding, masking and pre-paint readiness.','تجهيز السطح بالصنفرة والتغطية والتحضير قبل الدهان.'],
 ['Finish & Polish','التشطيب والتلميع','A final presentation layer focused on gloss, cleanliness and visual finish.','مرحلة نهائية تركز على اللمعان والنظافة وجودة المظهر.']
];
const steps=[['01','Inspect','فحص'],['02','Prepare','تجهيز'],['03','Mask','تغطية'],['04','Paint','دهان'],['05','Finish','تشطيب']];
export default function App(){
 const [lang,setLang]=useState<Lang>('en'); const [menu,setMenu]=useState(false); const t=copy[lang]; const rtl=lang==='ar';
 useEffect(()=>{document.documentElement.dir=rtl?'rtl':'ltr';document.documentElement.lang=lang},[lang,rtl]);
 const wa='https://wa.me/97471270891?text='+encodeURIComponent(lang==='ar'?'السلام عليكم، أريد الاستفسار عن دهان سيارتي.':'Assalamu Alaikum, I would like to ask about painting/refinishing my car.');
 return <main className={rtl?'rtl':''}>
  <header><a className="brand" href="#home"><span className="brandMark">M</span><span><b>MASUD</b><small>AUTO PAINT ZONE</small></span></a><nav>{t.nav.map((n,i)=><a key={n} href={'#'+['home','services','process','work','contact'][i]}>{n}</a>)}</nav><div className="headActions"><button className="lang" onClick={()=>setLang(rtl?'en':'ar')}><Languages size={18}/>{rtl?'EN':'العربية'}</button><a className="miniCall" href="tel:+97471270891"><Phone size={17}/></a><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
  {menu&&<div className="mobileNav">{t.nav.map((n,i)=><a onClick={()=>setMenu(false)} key={n} href={'#'+['home','services','process','work','contact'][i]}>{n}</a>)}</div>}
  <section id="home" className="hero"><img src="/images/hero-painted-car.png" alt="Beautifully painted SUV in an auto paint workshop"/><div className="heroShade"/><div className="heroContent"><div className="eyebrow"><span></span>{t.eyebrow}</div><h1>{t.hero}</h1><p>{t.sub}</p><div className="heroBtns"><a className="primary" href={wa} target="_blank"><MessageCircle size={20}/>{t.quote}<ArrowRight size={18}/></a><a className="ghost" href="tel:+97471270891"><Phone size={19}/>{t.call}</a></div><div className="proof"><BadgeCheck/><span>{t.proof}</span></div></div><div className="heroCard"><small>{rtl?'تواصل مباشر':'DIRECT CONTACT'}</small><b>+974 7127 0891</b><span><MapPin size={15}/>{t.location}</span></div></section>
  <section id="services" className="section light"><div className="sectionTop"><div><span className="kicker">{rtl?'الخدمات':'SERVICES'}</span><h2>{t.services}</h2></div><p>{t.servicesSub}</p></div><div className="serviceGrid">{services.map((s,i)=><article key={s[0]}><div className="serviceIcon">{[<Paintbrush/>,<Car/>,<Wrench/>,<Sparkles/>][i]}</div><small>0{i+1}</small><h3>{rtl?s[1]:s[0]}</h3><p>{rtl?s[3]:s[2]}</p><a href={wa} target="_blank">{rtl?'استفسر الآن':'Ask on WhatsApp'} <ChevronRight size={16}/></a></article>)}</div></section>
  <section id="process" className="process"><div className="processImage"><img src="/images/workshop.png"/><div className="floating"><ShieldCheck/><span><b>{rtl?'الاهتمام بالتفاصيل':'Detail-focused presentation'}</b><small>{rtl?'من التجهيز إلى التشطيب':'From preparation to finish'}</small></span></div></div><div className="processText"><span className="kicker gold">{rtl?'طريقة العمل':'THE PROCESS'}</span><h2>{t.process}</h2><p>{rtl?'هذا القسم يوضح للعميل رحلة العمل بشكل بسيط واحترافي. يتم تأكيد خطوات العمل الفعلية مع الورشة قبل النشر النهائي.':'This section gives customers a simple, premium view of the job journey. The workshop’s exact real-world process should be confirmed before final publication.'}</p><div className="steps">{steps.map(s=><div className="step" key={s[0]}><b>{s[0]}</b><span>{rtl?s[2]:s[1]}</span></div>)}</div><a className="textLink" href={wa} target="_blank">{t.quote}<ArrowRight size={17}/></a></div></section>
  <section id="work" className="section dark"><div className="sectionTop"><div><span className="kicker gold">{rtl?'النتائج':'TRANSFORMATIONS'}</span><h2>{t.transform}</h2></div><p>{t.transformSub}</p></div><div className="transformCard"><img src="/images/before-after-landcruiser.png"/><div className="transformNote"><span>{rtl?'صورة توضيحية للموقع التجريبي':'DEMO TRANSFORMATION VISUAL'}</span><b>{rtl?'لاند كروزر — قبل وبعد':'Land Cruiser — Before & After'}</b><p>{rtl?'تُستبدل بصور أعمال مسعود الحقيقية عند اعتماد الموقع.':'Replace with Masud’s real project photos when the website is approved.'}</p></div></div><div className="gallery"><figure><img src="/images/paint-booth.png"/><figcaption>{rtl?'مرحلة الدهان':'Paint application'}</figcaption></figure><figure><img src="/images/workshop.png"/><figcaption>{rtl?'تجهيز وتشطيب سيارات الدفع الرباعي':'SUV preparation & finish'}</figcaption></figure></div></section>
  <section className="trust"><div><b>5.0</b><span>{rtl?'التقييم في البيانات المرسلة':'Rating in supplied listing'}</span></div><div><b>6</b><span>{rtl?'مراجعات في البيانات المرسلة':'Reviews in supplied listing'}</span></div><div><b>AR / EN</b><span>{rtl?'موقع ثنائي اللغة':'Bilingual experience'}</span></div><div><b>1 TAP</b><span>{rtl?'واتساب واتصال مباشر':'WhatsApp & direct call'}</span></div></section>
  <section id="contact" className="cta"><div><span className="kicker gold">{rtl?'ابدأ الآن':'GET A QUOTE'}</span><h2>{t.contact}</h2><p>{t.contactSub}</p><div className="heroBtns"><a className="primary" href={wa} target="_blank"><MessageCircle size={20}/>{t.quote}</a><a className="ghost" href="tel:+97471270891"><Phone size={19}/>{t.phone}</a></div></div><div className="contactPanel"><MapPin/><span><small>{rtl?'الموقع':'LOCATION'}</small><b>{t.location}</b></span><Phone/><span><small>{rtl?'الهاتف / واتساب':'PHONE / WHATSAPP'}</small><b>+974 7127 0891</b></span></div></section>
  <footer><div className="brand"><span className="brandMark">M</span><span><b>MASUD</b><small>AUTO PAINT ZONE</small></span></div><p>{t.demo}</p><span>© 2026 Masud Auto Paint Zone — Website concept</span></footer>
  <a className="floatWa" href={wa} target="_blank" aria-label="WhatsApp"><MessageCircle/></a>
 </main>
}
